Add "must change password" mechanism + Normalize response for auth operations
noobaa/noobaa-core pull request #2021
Opened 2016-09-25 08:28 UTC by nb-ohad

### Purpose
- Allow setting a future date where the account will have to change it's password.
### Checklist
- Code:
  - [ ] User Experience: **Taken a moment to think the effects on our user**
  - [ ] Failure handling and Comments on non trivial sections: 
  - [ ] Cross Platform: **Supporting Win 7/8/10 Server 12, Linux, Mac**
- Testing:
  - [ ] Unit/System Tests: **Added tests ... / Already covered by existing tests ...**
  - [x] Tested with: `npm test`
- Supportability:
  - [ ] Diagnostics info, Phone Home info, ActivityLog events, External Syslog: 
- Upgrade:
  - [ ] Mongo Schema Upgrade:
  - [ ] Agents changes, Server Platform changes and New packages added to package.json:

2016-09-25 10:01 UTC, nimrod-becker approved these changes

2016-09-27 23:31 UTC, guymguym requested changes
fix `idate` usage (see comments)

2016-10-05 08:37 UTC, nimrod-becker approved these changes
Approve for the "Normalize account_info between read_auth and create_auth" part

2016-10-05 09:13 UTC, guymguym requested changes

2016-10-05 09:31 UTC, guymguym approved these changes

2016-10-05 09:47 UTC, merged