Fe sergi gaps session
noobaa/noobaa-core pull request #3452
Opened 2017-08-17 21:16 UTC by Sergii-Karpiak

### Explain the changes:
Replace stars bg to color 5 for the left and right boxes
Bucket Summary text - Change "spread/ mirrored on 2 pools" in bucket summary to "x resources"
Add links to configuration from the service status line
Add an explanation tooltip for S3 default placement
Same as the previous tooltip in create account
In permitted buckets list: show 3 buckets + #number more with tooltip
When allowed IPs/ permitted buckets list is long the user can't see all in the account details
Remove connect an application first step- replace wizard with a regular modal

### Issues (fixed #xxxx / opened technical debt #yyyy / partial fix to #zzzz)
fixed #3198

2017-08-27 12:38 UTC, nb-ohad approved these changes

2017-08-27 12:41 UTC, nimrod-becker submitted a review, later dismissed
See ohad's Review

2017-09-10 09:16 UTC, nb-ohad requested changes

2017-09-11 11:00 UTC, nb-ohad approved these changes

2017-09-11 11:36 UTC, merged