Added bucket_functions.js with common used bucket actions, tests updated to use bucket_functions
noobaa/noobaa-core pull request #4526
Opened 2018-02-28 15:59 UTC by EroolGui

### Explain the changes:
- added bucket_functions.js to src/test/utils
- updated namespace_test.js, rebuild_replicas_test.js, spillover_test.js to use bucket_fuctions methods

### Issues: Fixed / Gap #xxx
- 

### Testing Instructions:
- run namespace_test.js, rebuild_replicas_test.js, spillover_test.js 

### Reminders:
- Create a new test - the first is the hardest
- User Experience is top priority
- Design for failure
- Keep it simple
- `npm test`
- Imagine a support call - Add diagnostics info, phonehome info, activity log events, external syslog
- Upgrade - DB schema, server platform, agents install, npm packages

2018-03-04 08:52 UTC, nimrod-becker reviewed
In general, you've changed the way that errors were handled.
The original code caught exceptions and called for saveErrorAndResume which logged the problem, pushed it into a queue for later process and suppressed the exception.

Now we don't catch exceptions when we call to the bucket functions. You've implemented the function inside the bucket_functions.js but it simply logs the error, so we are missing the 
```
errors.push(message);
```
we used to have.

 I would suggest that instead of implementing the function in bucket_functions.js we can pass the function as a parameter (err_handler for example) to be used in the new functions whenever an error is caught.

What do you think ?

2018-03-05 08:55 UTC, liranmauda requested changes

2018-03-05 09:39 UTC, liranmauda requested changes

2018-03-06 09:53 UTC, liranmauda approved these changes

2018-03-06 09:54 UTC, merged