Removing the support for windows in the build
noobaa/noobaa-core pull request #5472
Opened 2019-05-20 13:09 UTC by liranmauda

### Explain the changes
We are no longer calling the win build in Build-Package.sh and not creating an exe

Build-Package.sh:
- Removing the support for windows

agent_functions.js:
- Removing the Win flavors from the  supported_oses

reclaim_test.js:
- not calling Win agents anymore

### Gaps:
1. Need to remove the handling of Win in the agent code
2. need to remove the Win referral from the UI

2019-05-20 14:37 UTC, jeniawhite requested changes

2019-05-20 14:37 UTC, jeniawhite commented on src/test/qa/reclaim_test.js
>  const osesLinuxSet = af.supported_oses('LINUX');
This should not have a param

2019-05-20 14:55 UTC, jeniawhite approved these changes

2019-05-21 05:57 UTC, nimrod-becker approved these changes
Notice that there might be some tests which rely on the number of agents created if using the supported_oses without a specific flavor. This will cause the #agents to be reduced from 11 to 8 just make sure it does not fail the tests . Also a reminder, remove the Jenkins Job

2019-05-21 07:07 UTC, merged