Ohad k8s pool changes
noobaa/noobaa-core pull request #5667
Opened 2019-08-13 17:06 UTC by nb-ohad

### Explain the changes
1.  Fix unmanaged pool deployment issues and UI
2. Fix - deployment script not deleting PVCs managed by the system
3. Managed hosts pools improvements

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

2019-08-14 07:47 UTC, dannyzaken requested changes

2019-08-14 07:47 UTC, dannyzaken commented on src/server/system_services/pool_server.js
> +                'hosts_pool_info.initialized': true,
`initialized` should be set after scale succeeds (inside `scale_hosts_pool_job`) and not here

2019-08-14 07:47 UTC, dannyzaken commented on src/server/system_services/pool_server.js
>              }
need to check here if not initialize and set `initialized=true`

2019-08-14 07:47 UTC, dannyzaken commented on src/server/system_services/pool_server.js
>      }
set initialized here if needed

2019-08-14 07:47 UTC, dannyzaken commented on src/server/system_services/pool_server.js
> +                    'hosts_pool_info.initialized': true,
no need to set initialized on delete

2019-08-15 18:33 UTC, dannyzaken commented on src/deploy/NVA_build/noobaa_pool.yaml
> +          # readinessProbe:
why did you eventually remove it? thought it was working with the probe

2019-08-16 06:06 UTC, nimrod-becker approved these changes

2019-08-16 07:55 UTC, merged