Fix deletion pool that was created as a backingstore  - when deleting from operator
noobaa/noobaa-core pull request #5884
Opened 2020-01-26 14:38 UTC by romayalon

### Explain the changes
1. Added check to find out if the caller of the delete pool / resource is operator.
2. fixed some redundant code.

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

2020-01-26 14:48 UTC, nb-ohad requested changes

2020-01-26 14:48 UTC, nb-ohad commented on src/server/system_services/pool_server.js
> +    if (reason && req.auth.role !== 'operator') {
What are you trying to check here?

2020-01-26 14:48 UTC, nb-ohad commented on src/server/system_services/pool_server.js
> +            if (reason && req.auth.role !== 'operator') {
Same as above

2020-01-26 14:59 UTC, nb-ohad requested changes

2020-01-26 14:59 UTC, nb-ohad commented on src/server/system_services/pool_server.js
> +    if (reason && req.auth.role !== 'operator') {
May I suggest:
```
const reason = check_pool_deletion(pool);
if (reason === IS_BACKINGSTORE) {
    const account_roles = req.account.roles_by_system[req.system._id];
    if (!account_roles.includes('operator')) {
        throw new RpcError(reason, 'Cannot delete pool');
    }
} else if (reason) {
    throw new RpcError(reason, 'Cannot delete pool');
}
```

2020-01-26 15:57 UTC, nimrod-becker approved these changes

2020-01-27 08:26 UTC, nb-ohad approved these changes

2020-01-27 08:27 UTC, merged