Get rid of discovering virtual appliance address
noobaa/noobaa-core pull request #6009
Opened 2020-05-06 18:59 UTC by paulxuzhang

### Explain the changes
1.  Disable discovering virtual appliance address if not in k8s deployment.

### Issues: Fixed #xxx / Gap #xxx
1. During local testing (the services started with npm on local machine), the IP address for the services will not be overwritten to public IP as result of discovering virtual appliance address, as the services don't listen to the public IP address.

### Testing Instructions:
1. The "hostname" for each service will stay as "127.0.0.1" in db.systems table.

2020-05-06 21:01 UTC, nb-ohad requested changes

2020-05-07 16:27 UTC, paulxuzhang commented on src/server/system_services/system_server.js
> +    }
Ok. I will take a look.

2020-05-12 17:28 UTC, nimrod-becker commented
@paulxuzhang can you please quash commits ?
@nb-ohad can you please re-review after the changes ?

2020-05-12 18:42 UTC, paulxuzhang commented
@nimrod-becker @nb-ohad Squashed commits.

2020-05-12 18:55 UTC, paulxuzhang commented
@nimrod-becker @nb-ohad Actually I did not do it right. If you really need one commit, we could do squash merge to master after approval or I could create separate PR.

2020-05-12 20:31 UTC, guymguym commented
@paulxuzhang No need for new PR. You can follow these steps:
```
git fetch upstream master:master
git rebase master
git reset --soft master
git commit
```

Another option is to do the squash interactively with `git rebase -i`

2020-05-12 21:03 UTC, paulxuzhang commented
@guymguym Thanks for the commands. Now only one commit.

2020-05-12 21:53 UTC, guymguym commented
++ @dannyzaken.
Just verifying - is there any reason we need this "external" IP when in Kubernetes?
Also there are two usages of this - in system_server and in server_monitor worker, are they both affecting the same?

2020-05-26 11:25 UTC, dannyzaken commented
@guymguym sorry, just now saw this comment. 
the `discover_virtual_appliance_address` is only used when not in kubernetes. don't see any reason we need it in kubernetes. 
looks like both usages, in system_server and server_monitor, have the same effect
maybe @nb-ohad has better answers

2020-05-31 20:09 UTC, guymguym commented
@dannyzaken Thanks, right, I missed that it's either-or.
@nb-ohad Can you approve then?

2020-06-10 03:06 UTC, guymguym commented
@nb-ohad ping

2020-06-10 10:51 UTC, nb-ohad approved these changes

2020-06-12 06:21 UTC, guymguym commented
@paulxuzhang Will you be able to rebase to complete this PR? thanks

2020-06-12 14:04 UTC, paulxuzhang commented
@guymguym Rebased

2020-06-12 14:30 UTC, merged