Addition of setting FS config for native
noobaa/noobaa-core pull request #6416
Opened 2021-03-17 16:42 UTC by jeniawhite

### Explain the changes
1. Added the capability to set fs config to the native layer to transfer uid, gid, backend and trigger ops with these values

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

2021-03-17 17:15 UTC, guymguym requested changes

2021-03-17 17:15 UTC, guymguym commented on src/native/fs/fs_napi.cpp
> +        , _orig_gid(getgid())
why do we need every op to record this? Why not do that globally once in our fs_napi_init function?

2021-03-17 17:15 UTC, guymguym commented on src/native/fs/fs_napi.cpp
> +        Napi::Object _config = info[0].As<Napi::Object>();
rename to `config` it's a local var not a class member.

2021-03-17 17:25 UTC, jeniawhite commented on src/native/fs/fs_napi.cpp
> +    virtual void Work() {
done

2021-03-18 11:46 UTC, guymguym approved these changes

2021-03-18 12:00 UTC, merged