Addition of FSync
noobaa/noobaa-core pull request #6700
Opened 2021-08-09 12:19 UTC by jeniawhite

### Explain the changes
1. Added FSync for I/O flows

### Issues: Fixed #xxx / Gap #xxx
1. Multipart upload as temp files that are renamed
2. FSync on reads for dual access when needed
3. Marking of FSynced files in the FS

### Testing Instructions:
1.

2021-08-09 14:24 UTC, liranmauda approved these changes
Just one question:
Do you want to keep the close of the dirs in the finally?
Why not use the same logic that we use on files and close it on the try block +  make sure with null that dir (but keep the finally just in case we error on the way)?

2021-08-09 17:15 UTC, BarakSason reviewed
Personally, I'd appreciate some more info in the commit message (why is this needed? High-level explanation on how is this implemented?).
Some in-code documentation would be appreciated as well.

2021-08-09 21:12 UTC, guymguym requested changes
Since our "update directory" code paths never really have the directory open with opendir (beccause it's only useful for reading entries one-by-one), then I think it makes more sense for fsync to be implemented once as an instance method for FileWrap - which you did, and second as a top api function (like rename) that takes a file/dir path and does open+fsync+close (instead of the DirWrap function). This will also simplify the error handling code needed from js. WDYT?

2021-08-10 12:01 UTC, jeniawhite commented
@liranmauda Removed the finally scope code due to usage of a function instead of opening a wrapper.
@BarakSason Please elaborate more on the information that is missing, you can read more at https://man7.org/linux/man-pages/man2/fdatasync.2.html to understand the high-level design, why it is used, and what the method does.

2021-08-10 13:17 UTC, liranmauda approved these changes
LGTM

2021-08-10 14:19 UTC, guymguym approved these changes

2021-08-10 14:56 UTC, merged

2021-08-10 19:17 UTC, guymguym commented on src/sdk/namespace_fs.js
> +            await nb_native().fs.fsync(fs_account_config, path.dirname(upload_path));
@jeniawhite Wait, isn't this the wrong path? we should be calling fsync on the target dir of the rename, which would be `path.dirname(file_path)` in this scope

2021-08-10 19:46 UTC, guymguym commented on src/sdk/namespace_fs.js
> +            await nb_native().fs.fsync(fs_account_config, path.dirname(upload_path));
There's a link() call few lines above this line, that I think needs fsync too - and there it's indeed on the dirname of upload_path. Generally it seems that we want to follow any update to the filesystem with an fsync call to the directory of the updated file... that includes all these natiive fs calls - rename, link, unlink, mkdir, rmdir, writeFile, open('w'). We also said we want to have a control flag to turn off fsync.