Azure library migration - Namespace flows - Part 1/4
noobaa/noobaa-core pull request #6744
Opened 2021-10-06 07:41 UTC by romayalon

Signed-off-by: Romy <romy2232@gmail.com>

### Explain the changes
1. WIP - Still have some TODOs to check in namespace blob.
2. this PR should be merged only after namespace tests PR https://github.com/noobaa/noobaa-core/pull/6743 will be completed and merged.
3. Required the new Azure library (https://github.com/Azure/azure-sdk-for-js) and created new wrap for the library.
4. Changed Namespace blob, namespace monitor and object_sdk with the needed changes.

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

2021-11-11 17:14 UTC, liranmauda requested changes

2021-11-11 17:14 UTC, liranmauda commented on src/sdk/namespace_blob.js
> +        size = parseInt(flat_obj.contentLength, 10);
```suggestion
       const size = parseInt(flat_obj.contentLength, 10);
```

2021-11-11 17:14 UTC, liranmauda commented on src/util/cloud_utils.js
> +    let endpoint_url = url.parse(params.endpoint);
```suggestion
    const endpoint_url = url.parse(params.endpoint);
```

2021-11-11 17:14 UTC, liranmauda commented on src/util/cloud_utils.js
> +function get_azure_new_connection_string(params) {
Let's add a TODO that when there will no need for both functions (`get_azure_connection_string` and 
`get_azure_new_connection_string` ) we can remove the old and rename the new

2021-11-11 17:14 UTC, liranmauda commented on src/util/new_azure_storage_wrap.js
> +var crypto = require("crypto");
```suggestion
const crypto = require("crypto");
```

2021-11-17 09:53 UTC, romayalon commented on src/sdk/namespace_blob.js
> +        this.old_blob = azure_storage.get_old_blob_service_conn_string(connection_string);
Added

2021-11-17 09:54 UTC, romayalon commented on src/sdk/namespace_blob.js
> +                params.delimiter, { prefix: params.prefix }).byPage({ continuationToken: params.key_marker, maxPageSize: max_keys});
yes

2021-11-17 09:54 UTC, romayalon commented on src/sdk/namespace_blob.js
> +            is_truncated: Boolean(response.continuationToken),
just continutationToken, so it's fine

2021-11-17 09:56 UTC, romayalon commented on src/sdk/namespace_blob.js
>      async commit_blob_block_list(params) {
@nimrod-becker @liranmauda we have these similar implementations in many other namespaces,
removing it from here is not enough,
shall I open a github issue so we will remove all the flow?

2021-11-17 09:56 UTC, romayalon commented on src/sdk/namespace_blob.js
>      async get_blob_block_lists(params) {
I commented on the other comment, resolving

2021-11-17 13:55 UTC, liranmauda approved these changes
LGTM

2021-11-17 14:30 UTC, merged