Force `rpc_address` to use `ws` as the protocol to avoid using ICE
noobaa/noobaa-core pull request #6841
Opened 2021-12-23 11:16 UTC by liranmauda

### Explain the changes

- Force rpc_address to use ws as the protocol to avoid using ICE
- Fixing the agent port to 60101

As decided we will leave the ICE code in for now and we will do a cleanup once we are 100% about it.
We want to clean the code in a later version, probably at 4.11

Signed-off-by: liranmauda <liran.mauda@gmail.com>

2021-12-23 21:38 UTC, guymguym requested changes
See comments on _authenticate_agent_api and wss-vs-ws

2021-12-23 21:38 UTC, guymguym commented on src/server/node_services/nodes_monitor.js
> +        const rpc_proto = 'ws';
shouldn't we be using `wss` for TLS?
n2n was configured to use TLS too - tcp_tls flag in n2n_config...

2021-12-28 07:24 UTC, liranmauda commented
Moving to draft.
2 topics here:
1. We need to decide what to do with the agent authentication. we will have a talk regarding @guymguym suggestion
2. Unit tests are failing as we scaling the agent locally and with this change it is failing on rpc_adress which was hardcoded into the same port (60101)

2022-09-13 08:13 UTC, dannyzaken commented
let's have a discussion on that and see how we want to advance with this PR with regards to also moving to node 16

2023-01-17 09:20 UTC, liranmauda commented
Open a Jira story: https://issues.redhat.com/browse/MCGI-126
Closing.

2023-01-17 09:20 UTC, closed without merging