Added AWS STS related unit tests
noobaa/noobaa-core pull request #6956
Opened 2022-05-10 08:05 UTC by ezio-auditore

Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>

### Explain the changes
1. Added missing AWS STS related unit tests

- [ ] Doc added/updated
- [x] Tests added

2022-05-10 08:14 UTC, ezio-auditore commented
requesting review @guymguym @dannyzaken

2022-05-10 19:23 UTC, guymguym requested changes
Hi @ezio-auditore Thanks! 
I'm happy to see how creatively you used sinon, it really helps a lot with gray-box unit-testing.

Few questions I had:
- Is this meant to be testing just the cloud_utils code? 
- Is this testing the STS support we use as a client to our cloud backing stores or namespace stores? 
- Or is it for STS support of noobaa endpoints to its clients?
- In both cases I would define a test which is invoking this functionality as black-box like clients do (in case of backing stores it means to create a backing store with STS configuration and then invoke it while mocking the backing store).

Gray-box is great for really complex to sample logic where a tiny hook really slices it well, but is cloud_utils logic not too shallow for that? In any case, I'll let @dannyzaken review as well, and I don't mind having this as a base, and followup in subsequent PRs. Thanks!

2022-05-10 19:23 UTC, guymguym commented on src/test/unit_tests/test_aws_sts.js
> +        ];
we use the jsbeautifier settings - in vscode there's the HookyQR.beautify extension that will do it -
```suggest
        const expectedParams = [{
            RoleArn: roleArn,
            RoleSessionName: 'testSession',
            WebIdentityToken: 'web-identity-token',
            DurationSeconds: defaultSTSCredsValidity,
        }];
```

2022-05-10 19:23 UTC, guymguym commented on src/test/unit_tests/test_aws_sts.js
> +        STSStub.restore();
This restore() will not be called if this test fails before it.
The way to do it safer in mocha is to use mocha.before(...) and mocha.after(...)
See here for example:
https://github.com/ezio-auditore/noobaa-core/blob/92ec8ead6284c69badc581e9e9d1d5b7c2b624b6/src/test/unit_tests/test_namespace_fs.js#L53-L62

2022-05-10 19:23 UTC, guymguym commented on src/test/unit_tests/test_aws_sts.js
> +mocha.describe('AWS STS tests', function() {
If you want this to run as part of the unit tests you should add it to `src/test/unit_tests/index.js`

2022-05-18 05:30 UTC, ezio-auditore commented
> Hi @ezio-auditore Thanks! I'm happy to see how creatively you used sinon, it really helps a lot with gray-box unit-testing.
> 
> Few questions I had:
> 
> * Is this meant to be testing just the cloud_utils code?
> * Is this testing the STS support we use as a client to our cloud backing stores or namespace stores?
> * Or is it for STS support of noobaa endpoints to its clients?
> * In both cases I would define a test which is invoking this functionality as black-box like clients do (in case of backing stores it means to create a backing store with STS configuration and then invoke it while mocking the backing store).
> 
> Gray-box is great for really complex to sample logic where a tiny hook really slices it well, but is cloud_utils logic not too shallow for that? In any case, I'll let @dannyzaken review as well, and I don't mind having this as a base, and followup in subsequent PRs. Thanks!

This is meant to test just the cloud_utils code. Since I was not sure how I can mock the creation of backingstores.
Are there already existing tests I can refer to with regards to this?

2022-06-09 14:26 UTC, dannyzaken approved these changes
LGTM

2022-06-15 12:05 UTC, guymguym commented
Hi @ezio-auditore, Thanks for the explanation, so I guess in that case I would just rename the file to `test_cloud_utils.js`.

2022-06-15 14:56 UTC, guymguym approved these changes

2022-06-15 14:56 UTC, merged