GitHub actions - multiarch
noobaa/noobaa-core pull request #7038
Opened 2022-08-09 14:49 UTC by baum

- multiarch build with a manifest
- depends on https://github.com/noobaa/noobaa-core/pull/7028

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>

2022-09-05 11:21 UTC, nimrod-becker commented
Testing some actions issues , closing for now

2022-09-20 08:06 UTC, liranmauda commented
@nimrod-becker Can you open a new branch for testing this PR?

2022-09-20 17:12 UTC, nimrod-becker commented
Sure, do you want me to create an upstream branch and we can merge this to that branch and then merge the branch once stable to master?

2022-09-21 15:55 UTC, baum commented
The new action has to be tested. Could anyone trigger a controlled test run of the new manual build?

Best regards 🖖

2023-01-19 10:27 UTC, dannyzaken commented on .github/workflows/manual-full-build.yaml
> +      - name: Push Docker Images to DockerHub
@baum let's remove the push steps. for now we can use this action as a test for our build process and make sure that arm builds are not broken. later on, we can use it to publish multiarch builds, after we have testing pipeline for that

2023-01-19 10:30 UTC, dannyzaken requested changes
Currently, it is changing the manual-full-build action. let's change it to a separate action

2023-02-09 12:19 UTC, jackyalbo commented
@baum this PR isn't progressing for a while - maybe we should move to draft

2023-06-04 11:52 UTC, closed without merging