Add experimental support for STS CLI usage
noobaa/noobaa-core pull request #7605
Opened 2023-11-16 15:57 UTC by Neon-White

### Explain the changes
Currently, NooBaa overrides various AWS signing processes, which eventually leads to some authentication failures - e.g. when trying to use AWS CLI for STS operations.
I fixed the problem by repurposing an already-existing body checksum calculation, and assigning it to `content_sha256_sig` in case it wasn't yet assigned. Since the NooBaa signature process already utilizes it, no further changes were required.

2023-11-28 14:01 UTC, romayalon commented on src/util/signature_utils.js
> +    if (req.body && service === 'sts') {
so do we need to add a body for all sts actions or just to assume role? can you maybe share a link for why this is the needed solution?
Also, doesn't this affect non cli requests? how things are not failing on the sts sdk tests?

2023-11-28 14:01 UTC, romayalon commented on src/util/signature_utils.js
> +
sts cli tests are needed

2023-12-05 09:05 UTC, dannyzaken approved these changes

2023-12-06 00:32 UTC, guymguym requested changes

2023-12-21 11:00 UTC, guymguym submitted a review, later dismissed

2023-12-21 11:00 UTC, guymguym commented on src/util/http_utils.js
> +                req.body_sha256_calc_by_nb = AWS.util.crypto.sha256(req.body, 'hex');
Hmm, so I see that we already calculate the incoming content sha256 in the end of `read_request_body()` and we save it in `req.content_sha256_buf` so this calculation is actually redundant in any case. 

I am not sure if this fits all cases but it seems that you could just do this generally in read_request_body:
```
                req.content_sha256_buf = sha256_buf;
                req.content_sha256_sig ||= sha256_buf;
```

2024-01-09 13:05 UTC, guymguym approved these changes
👍

2024-01-10 15:52 UTC, merged